stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - data/raw/diabetes.csv
      - src/preprocess.py
    outs:
      - data/processed/test.csv
      - data/processed/train.csv

  train:
    cmd: python src/train.py
    deps:
      - data/processed/train.csv
      - src/train.py
    params:
      - models  # Tell DVC to watch the "models" list in params.yaml
    outs:
      - models/  # Track the entire folder since filenames now contain model names

  validate:
    cmd: python src/validate.py
    deps:
      - data/processed/test.csv
      - models/
      - src/validate.py
    metrics:
      - metrics/metrics.json:
          cache: false
    plots:
      - plots/confusion_matrix.png:
          cache: false